version: '3.9'

services:
  db:
    image: postgres:17
    container_name: movie_postgres
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: movie_recommendation
      POSTGRES_USER: movie_user
      POSTGRES_PASSWORD: movie_password
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: movie_redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: movie_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  web:
    build: .
    container_name: movie_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis
      - rabbitmq

  worker:
    build: .
    container_name: movie_worker
    command: celery -A movie_recommendation_web worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
      - rabbitmq
    env_file:
      - .env.dev

volumes:
  postgres_data: {}
