version: '3.9'

services:
  web:
    build: .
    container_name: movie_web
    command: gunicorn movie_recommendation_web.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.prod

  worker:
    build: .
    container_name: movie_worker
    command: celery -A movie_recommendation_web worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env.prod
    depends_on:
      - web
