# Generated by Django 5.2.6 on 2025-09-28 12:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('watched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('watched_duration', models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('completed', models.BooleanField(default=False, help_text='whether the user watched to the end')),
                ('playback_position', models.PositiveIntegerField(blank=True, help_text='Last know playback position in seconds', null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_histories', to='movies.moviereference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interactions_watch_history',
                'ordering': ['-watched_at'],
                'indexes': [models.Index(fields=['user', 'movie'], name='interaction_user_id_c09b97_idx'), models.Index(fields=['movie', 'watched_at'], name='interaction_movie_i_993504_idx')],
            },
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('want_to_watch', 'want_to_watch'), ('watching', 'watching'), ('completed', 'completed')], default='want_to_watch', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='Optional priority (higher => show earlier)')),
                ('notes', models.TextField(blank=True, default='')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_entries', to='movies.moviereference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interactions_watchlist',
                'ordering': ['-added_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='interaction_user_id_22effb_idx'), models.Index(fields=['movie', 'status'], name='interaction_movie_i_69719e_idx')],
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
