# Generated by Django 5.2.6 on 2025-09-26 19:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tmdb_genre_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='MovieReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tmdb_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('imdb_id', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('title', models.CharField(db_index=True, max_length=512)),
                ('poster_path', models.CharField(blank=True, max_length=512, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('popularity', models.FloatField(default=0.0)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movie_reference',
                'ordering': ['-popularity'],
                'indexes': [models.Index(fields=['title'], name='movie_refer_title_305164_idx'), models.Index(fields=['popularity'], name='movie_refer_popular_ce649a_idx')],
            },
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.genre')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.moviereference')),
            ],
        ),
        migrations.CreateModel(
            name='MovieDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overview', models.TextField(blank=True, null=True)),
                ('runtime', models.PositiveIntegerField(blank=True, null=True)),
                ('original_language', models.CharField(max_length=8, null=True)),
                ('vote_average', models.FloatField(default=0.0)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='movies.moviereference')),
            ],
            options={
                'db_table': 'movie_detail',
            },
        ),
    ]
